### ISSUE TITLE
Add gbyte functions to bacio

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-bacio#105]
It was discovered that the gybte functions are duplicated in g2 and w3emc (w3nco before the merge). This library seems like the most logical place to hold these functions as it concerns byte i/o manipulation and g2/w3emc already use bacio.

See discussion at https://github.com/NOAA-EMC/NCEPLIBS-g2/issues/235

**Comment by edwardhartnett** [comment]
I don't believe we will do this. More likely we'll solve the gbyte problem by combining g2 and w3emc.
