### ISSUE TITLE
Update README to NCEPLIBS standards

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bacio#29]
See https://github.com/NOAA-EMC/NCEPLIBS/issues/120

**Comment by edwardhartnett** [comment]
@Hang-Lei-NOAA we say:

> Performs I/O for the NCEP models.

Can we be more specific? What kind of I/O?

**Comment by Hang-Lei-NOAA** [comment]
Specifically, it is processing unformatted Byte-addressable data records.
It transformat the little endian files and big endian files.
